# Spring: DB Connection Setting
spring:
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  web:
    resources:
      cache:
        period: 0
      chain:
        cache: false
  datasource:
    url: ENC(6iRnEl1xtSQJE7zXIhxRhNx3gvABkZVnLmzpcZiMAU09cvtaf3+BdShtCP8mDPN6FIkHVGgcDVLVeQYRrggvsPIfeIjEHJETQIxVZ5dbGKdk2ZuM/PQHhQ==)
    username: ENC(Rk+uQ5wPH/u+0KR87yEEQbbHeMeg1bHGWDWVZzOPXwc=)
    password: ENC(Adzo5IfQ1LoH+ahoJ3Gj5ExK8z2y9VR/H5keTCQ7P1M=)

  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      location: /tmp
  data:
    redis:
      host: ENC(gURsw5RjnsEJwzR1IHreE3xU8ILlN5QGMGKUKJajbOw=)
      port: 6380
      password: ENC(EBzA5fEjO/SrQVy7LOAA6Y+t4SH75wF2etEi6embBM8=)

server:
  forward-headers-strategy: native

file:
  upload-dir: /upload_img_tb
jasypt:
  encryptor:
    algorithm: PBEWithHMACSHA512AndAES
    bean: jasyptStringEncryptor
    password: ${ENCRYPTION_KEY}

kakao:
  token:
    uri: https://kauth.kakao.com/oauth/token
  user-info:
    uri: https://kapi.kakao.com/v2/user/me
  terms-info:
    uri: https://kapi.kakao.com/v2/user/service_terms?result=app_service_terms
  client:
    id: ENC(P73y2VT13lK7uUkgrUaiU24UmgLWvJAILpOsPgEItlOGhtF+YBlantl3voDN1iYpbvDBuAHyM8s=)
    redirect-uri: https://tb.smtong.co.kr/auth/kakao/callback
    scope:
      - account_email
      - name
      - phone_number
# Scraping
scraping:
  server: http://172.17.0.1:5001

#host company api
gogo:
  api:
    base-url: https://api.gogofactory.co.kr
    auth-key: 057485accc44c076e27b7fa2328232e4
    order-req-url: /info/semo/online_order.php
    order-state-query-url: /info/semo/online_memo.php
minigate:
  api:
    base-url: https://dev.shakemobile.co.kr
    auth-key: 570b7be77c423c81cd05dc67babe4fa0d0fd0dca46c9f952bf990758cac89c741a525be560bd82cfe533ed254accd38119c6540370185501fc27a66849c5dfd4
    order-req-url: /M2Mobile/v1/api/partner/member/recv
    enc-key: mMvno0105Mgm@!gm
    vector: (byte)0x26, (byte)0x8D, (byte)0x66, (byte)0xA7, (byte)0x35, (byte)0xA8, (byte)0x1A, (byte)0x81, (byte)0x6F, (byte)0xBA, (byte)0xD9, (byte)0xFA, (byte)0x36, (byte)0x16, (byte)0x25, (byte)0x01
    client-id: VMG0016
#DAOU
daou:
  url: https://test-box-api.addcon.co.kr
  partner-code: PAKED7
  key:
    api-key: SuTPg735wUypp1WttPMdpdl9t9jWdT1g
    enc-key: wj7Z5ylj2iD7iST5tKO1JIF1Yj8eEfsz
    iv-key: wj7Z5ylj2iD7iST5
#BIZPPURIO
bizppurio:
  kakao:
    url: https://api.bizppurio.com
    id: semotong
    password: smtongdaebak1^^
    fromNum: 070-5038-5883
    senderkey: 7012483899c61b22b0832cca13a2311be0526b76
    apikey: mxzVXEeTmbWW
#tinymce:
#  apikey: j4d697kj1fbwoojkxx8ofo5k459y680knp9ds4abehjnvrhg
#  apikey: kwp5a1sz2dzruj23zt25uena48j21yiksw11eqe7sw77xfmc
#  apikey: hs4eicxfwfmtmdmgaw27483ir4dfhl2qhzvam162wgagg7by
#  apikey: yo1dk44p8erx3a2rf6bprnb4zlnnq6gk2olhbakkno8t2h7t
#  apikey: pf0yclpn7jrxudxxx0ybmvy9vnbib08acp6alc0f9bd6v1kw
#  apikey: msoz9q348s6y1ti7az3ytf0x2ka1hhdkai8zsr8osnz6506n

